name: GitFlow
description: Magna's GitFlow implementation
author: Magna Inc
inputs:
  token:
    required: true
    description: GitHub token
  operation:
    required: true
    description: Which operation of the action is getting triggered? One of create_release | update_release | publish_release | hotfix_release
  major:
    description: Is this a major version release?
    default: "false"
  cycle:
    description: Which cycle is the release for?
runs:
  using: 'node16'
  main: 'dist/index.js'
