name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: Features 🚀
    labels: [feature]
  - title: Fixes 🪲
    labels: [bug]
  - title: Chores 🧰
    labels: [chore]
change-template: "* $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: No changes
version-resolver:
  major:
    labels: [major]
  minor:
    labels: [feature]
  patch:
    labels: [bug, chore]
  default: minor

template: |
  ## What's Changed

  $CHANGES

replacers:
  - search: "[feature]"
    replace: ""
  - search: "[bug]"
    replace: ""
  - search: "[chore]"
    replace: ""
