on:
  workflow_dispatch:
    inputs:
      major:
        type: boolean
        description: Is this a major release?
        default: false
      cycle:
        type: number
        description: What is the cycle number?
        required: true

name: Create Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      - name: Build action
        working-directory: action
        run: yarn && yarn build
      - name: Create Release
        uses: ./action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          operation: create_release
          major: ${{ github.event.inputs.major }}
          cycle: ${{ github.event.inputs.cycle }}
