on:
  push:
    branches:
      - dev

concurrency:
  group: dev
  cancel-in-progress: true

name: Deploy Dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        run: echo 'deploy dev'
