on:
  push:
    branches:
      - main

concurrency:
  group: prod
  cancel-in-progress: true

name: Deploy Prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        run: echo 'deploy prod'
