on:
  push:
    branches:
      - 'release/*'
      - '!release/**-dev'

concurrency:
  group: staging
  cancel-in-progress: true

name: Deploy Staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        run: echo 'deploy staging'
