on:
  push:
    branches:
      - release/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: Update Release

jobs:
  update-release:
    name: Update Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build action
        working-directory: action
        run: yarn && yarn build
      - name: Update Release
        uses: ./action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          operation: update_release
